### ISSUE TITLE
Test monitoring.coreos.com/v1 Probe

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/fdk-infra#84]
```yaml
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: probes
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: monitoring-blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
      - <url>
```
